#include <atl.hpp>
#include <iostream>
#include <sstream>
/* Takes lines of code from cin and prints the generated byte-code to cout. */

using namespace atl;

int main()
{
	Atl atl;
	std::string buffer;

	try
		{
			while(true)
				{
					std::cout << "input command (prefixed by :) or some Atl to parse: " << std::flush;
					std::getline(std::cin, buffer);

					if(buffer.empty())
						{ break; }

					if(buffer[0] == ':')
						{
							std::stringstream rest;
							rest << buffer;

							std::string head;
							rest >> head; // ditch the ':'
							rest >> head;

							if(head == "resolve-patches")
								{
									atl.compile.resolve_backtracks();
									atl.compile.code_store.dbg();
								}
							if(head == "quit")
								{ break; }
						}
					else
						{
							atl.compile.any(atl.parse.string_(buffer));
							std::cout << "Done parsing; code generating byte-code...:" << std::endl;
							atl.compile.code_store.dbg();
						}
				}
		}
	catch(std::string str)
		{
			std::cout << str << std::endl;
		}
	catch(std::runtime_error err)
		{
			std::cout << err.what() << std::endl;
		}

	return 0;
}
